### PR TITLE
Added various Updates in SettingsView

### PR DESCRIPTION
**Pull request by henryphz**

### CODE REVIEW

**Comment by samuelgin** [comment]
!!!! please never remove an entitlement and commit the change!! (in sentimizer.entitlements file). we can't add these entitlements without a paid apple developer account! please revert this change.

**Comment by samuelgin** [comment]
will review other changes of this PR later today.

**Comment by henryphz** [comment]
Entitlements file restored

**Comment by samuelgin** [comment]
Please remove the print statement in `SentimizerApp.swift` if you dont need it
`for family in UIFont.familyNames.sorted() {
                         let names = UIFont.fontNames(forFamilyName: family)
                         print("Family: \(family) Font names: \(names)")
                     }`

**Comment by samuelgin** [comment]
If your new font supports multiple font weights, you dont need seperate Font extensions (`sentiLight`, `sentiMedium` etc). You can simply adjust the font weight by adding the `.fontWeight(...)` modifier to the text you want a special weight to apply to. You have to add the font in a single .ttf file for this to work.

**Comment by samuelgin** [comment]
Please add modifiers on the next line if its more than one (e. g. `Section(header: Text("Color Scheme").font(.sentiLight(size: 13)).foregroundColor(.gray)) {`)

**Comment by henryphz** [comment]
Added requested changes

**Review by samuelgin — APPROVED** [review]

**Pull request merged**
